# Settings
exclude:
  [
    ".github",
    "Gemfile",
    "Gemfile.lock",
    "build.sh",
    "README.md",
    "CNAME",
  ]
permalink: pretty

collections_dir: collections
collections:
  article:
    output: true

defaults:
  - scope:
      path: ""
      type: "article"
    values:
      layout: "article"

plugins:
  - jekyll-paginate-v2

# Pagination (used by the blog)
pagination:
  enabled: true
  debug: false

  collection: "article"
  per_page: 24
  sort_field: "date"
  sort_reverse: true
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # title: ":title - Page :num"
  permalink: "/:num/"
  category: "posts"
  tag: ""
  locale: ""
